### ISSUE TITLE
example 不能测试通过

### ISSUE THREAD

**Issue by snwyz** [xiaomingplus/weibo-simulation-api#1]
我是这样写的 - -；

![1](https://user-images.githubusercontent.com/20658775/30256820-01d6c688-96e0-11e7-8f70-4c96f1dadf79.png)
 运行就报了 data null

**Comment by xiaomingplus** [comment]
看不出是什么问题，我这测试了3个账号都ok，你可以clone下去调试下。或者账号密码给我也可以。记得node版本也升级到最新版。我的example用了新特性。

**Comment by UnscientificMisaka** [comment]
@Artmagic 您应该开启了登录保护，关掉就可以了

**Comment by huashengzhang** [comment]
win10
node：v8.7.0
错误也是data null
我在想是不是环境问题，昨天晚上在mac上是没有问题

**Comment by huashengzhang** [comment]
@xiaomingplus

**Comment by huashengzhang** [comment]
我修改了src/api/index.js
造成的原因：
在window下去读取文件获取到的路径对应不上，导致data null

![qq 20171114135929](https://user-images.githubusercontent.com/31681100/32765171-44d0cea2-c944-11e7-9200-8e78ff4bb3d7.png)




其实我是不理解这里为什么要去读取文件，默认为存在即可
module.exports = function (api, params) {
    return  require('./statuses/share')(params)
}

**Comment by xiaomingplus** [comment]
已经发了新版本解决了windows下的路径问题了。更新即可。

----
其实我是不理解这里为什么要去读取文件，默认为存在即可
----
这里是为了以后扩展考虑的，目前只支持这一个接口，以后可能会支持很多接口。所以这里用文件来区分每一个api。
